name: easy_way
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  auto_route: ^10.1.0+1
  bloc: ^9.0.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_typeahead: ^5.2.0
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  geolocator: ^14.0.2
  get_it: ^8.1.0
  google_maps_flutter: ^2.12.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  injectable: ^2.5.1
  intl: ^0.20.2
  json_serializable: ^6.9.5
  latlong2: ^0.9.1
  open_route_service: ^1.2.7
  retrofit: ^4.7.0

dev_dependencies:
  auto_route_generator: ^10.2.3
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.7.0
  mocktail: ^1.0.4
  retrofit_generator: ^9.7.0
  very_good_analysis: ^9.0.0


flutter:
  generate: true
  uses-material-design: true

# AIzaSyBz0UPCuugr7DW6qY0wuGnRQF-8DnE6f08